openapi: 3.2.0
info:
  title: Bench Project Notes API
  description: 'Versioning


    The API is currently at version 1.0.'
  version: '1.0'
servers:
- url: https://bench.gobridgit.com
  description: Bridgit Bench production
security:
- {}
tags:
- name: ProjectNotes
paths:
  /rp/api/v1/accounts/{accountId}/projects/{projectId}/notes:
    get:
      tags:
      - ProjectNotes
      summary: Gets all notes on the given account's project
      description: 'Permissions

        Project: Read

        Private: Read'
      operationId: ProjectNotes_Query
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: projectId
        in: path
        description: The project ID the note belongs to
        required: true
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: Offset for pagination
        schema:
          maximum: 2147483647
          minimum: 0
          type: integer
          format: int32
          default: 0
      - name: limit
        in: query
        description: Maximum number of results per page
        schema:
          maximum: 2147483647
          minimum: 1
          type: integer
          format: int32
          default: 100
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NoteResponse'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NoteResponse'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NoteResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      tags:
      - ProjectNotes
      summary: Adds a note on the given account's project
      description: 'When trying to create a private note you must have permissions to manage private values in the account.


        When trying to mention a user, you must provide their userID in the following pattern [[mention:userID#123]].

        Permissions

        Project: Read

        Private: Write'
      operationId: ProjectNotes_Add
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: projectId
        in: path
        description: The project ID to add the note to
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Request object that contains the message and whether or not the note is private
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/NewNoteRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/NewNoteRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/NewNoteRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/NewNoteRequest'
        required: true
      responses:
        '201':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/NewNoteResponse'
              example:
                id: 213
                message: This is a note about something on the project.
                isPrivate: false
                creatorId: 453
                creatorName: John Smith
                createdOn: '2021-05-27T10:47:23.53'
                lastModifiedOn: '2021-05-27T10:47:23.53'
            application/json:
              schema:
                $ref: '#/components/schemas/NewNoteResponse'
              example:
                id: 213
                message: This is a note about something on the project.
                isPrivate: false
                creatorId: 453
                creatorName: John Smith
                createdOn: '2021-05-27T10:47:23.53'
                lastModifiedOn: '2021-05-27T10:47:23.53'
            text/json:
              schema:
                $ref: '#/components/schemas/NewNoteResponse'
              example:
                id: 213
                message: This is a note about something on the project.
                isPrivate: false
                creatorId: 453
                creatorName: John Smith
                createdOn: '2021-05-27T10:47:23.53'
                lastModifiedOn: '2021-05-27T10:47:23.53'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Unprocessable Entity - Limit for for number of notes reached
  /rp/api/v1/accounts/{accountId}/projects/{projectId}/notes/{id}:
    get:
      tags:
      - ProjectNotes
      summary: Gets a note on the given account's project by id
      description: 'Permissions

        Project: Read

        Private: Read'
      operationId: ProjectNotes_Get
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: projectId
        in: path
        description: The project ID the note belongs to
        required: true
        schema:
          type: integer
          format: int64
      - name: id
        in: path
        description: The ID of the note
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/NoteResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/NoteResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/NoteResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    patch:
      tags:
      - ProjectNotes
      summary: Updates a note on the given account's project
      description: 'When trying to update a note''s privacy you must have permissions to manage private values in the account.


        Only the creator of a note can edit it.


        When trying to mention a user, you must provide their userID in the following pattern [[mention:userID#123]].

        Permissions

        Project: Read

        Private: Write'
      operationId: ProjectNotes_Update
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: projectId
        in: path
        description: The project ID the note is on
        required: true
        schema:
          type: integer
          format: int64
      - name: id
        in: path
        description: The ID of the note to update
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Request object that contains the message and whether or not the note is private
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/UpdateNoteRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNoteRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateNoteRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateNoteRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/NoteResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/NoteResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/NoteResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    delete:
      tags:
      - ProjectNotes
      summary: Deletes a note from the given account's project
      description: 'Only the creator or an account admin can delete it.

        Permissions

        Project: Read

        Account: Write'
      operationId: ProjectNotes_Delete
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: projectId
        in: path
        description: The project ID the note is on
        required: true
        schema:
          type: integer
          format: int64
      - name: id
        in: path
        description: The ID of the note to update
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '204':
          description: Success
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    NoteResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 213
        message:
          type:
          - string
          - 'null'
          example: This is an updated message on a note.
        isPrivate:
          type: boolean
          example: false
        creatorId:
          type: integer
          format: int32
          example: 453
        creatorName:
          type:
          - string
          - 'null'
          example: John Smith
        createdOn:
          type: string
          format: date-time
          example: '2021-05-27T10:47:23.530Z'
        lastModifiedOn:
          type: string
          format: date-time
          example: '2021-05-27T10:58:23.530Z'
      additionalProperties: false
    NewNoteRequest:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
          example: This is a note about something on the project. This is mentioning [[mention:userID#123]] to notify them.
        isPrivate:
          type: boolean
          example: false
      additionalProperties: false
    NewNoteResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 213
        message:
          type:
          - string
          - 'null'
          example: This is an updated message on a note.
        isPrivate:
          type: boolean
          example: false
        creatorId:
          type: integer
          format: int32
          example: 453
        creatorName:
          type:
          - string
          - 'null'
          example: John Smith
        createdOn:
          type: string
          format: date-time
          example: '2021-05-27T10:47:23.530Z'
        lastModifiedOn:
          type: string
          format: date-time
          example: '2021-05-27T10:58:23.530Z'
      additionalProperties: false
    UpdateNoteRequest:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
          example: This is an updated message on a note, this is mentioning [[mention:userID#123]] to notify them.
        isPrivate:
          type:
          - boolean
          - 'null'
          example: false
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      description: Standard Authorization header using the Bearer scheme
      scheme: bearer
      bearerFormat: JWT
