openapi: 3.2.0
info:
  title: Bench Persons API
  description: 'Versioning


    The API is currently at version 1.0.'
  version: '1.0'
servers:
- url: https://bench.gobridgit.com
  description: Bridgit Bench production
security:
- {}
tags:
- name: Persons
paths:
  /rp/api/v1/accounts/{accountId}/Persons:
    get:
      tags:
      - Persons
      summary: Gets all people in the given account
      description: 'NOTE: If there are more persons in the account than were returned, there will be a "query-has-more" header that will be set to true.

        Permissions

        HourlyProfile: Read

        Person: Read

        Finance: Read'
      operationId: Persons_Query
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: relativeDate
        in: query
        description: Optional paramater used to calculate date based properties. If not provided, it is set to today's date in UTC.
        schema:
          type: string
          format: date-time
          example: '2021-01-01'
        example: '2021-01-01'
      - name: offset
        in: query
        description: Offset for pagination
        schema:
          maximum: 2147483647
          minimum: 0
          type: integer
          format: int32
          default: 0
      - name: limit
        in: query
        description: Maximum number of results in this page
        schema:
          maximum: 2147483647
          minimum: 1
          type: integer
          format: int32
          default: 1000
      - name: email
        in: query
        description: Filter user with email
        schema:
          type: string
      - name: state
        in: query
        description: 'If specified and not ''Unknown'', only include people matching the given state. The available values are defined as follows:

          - Unknown: By default, includes only Active people.

          - Active: include only Active people

          - Deactivated: include only Deactivated people

          - All: include all people, regardless of state'
        schema:
          enum:
          - Active
          - Deactivated
          - All
          type: string
          default: Active
      - name: ids
        in: query
        description: Optional paramater of comma delimited ids for filtering results based on the person IDs provided
        schema:
          type: array
          items:
            type: integer
            format: int64
      - name: uniqueId
        in: query
        description: Optional paramater of unique identifier for filtering results based on the person unique identifier provided
        schema:
          type: string
      responses:
        '200':
          description: 'Success: List of persons in the account'
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonResponse'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonResponse'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      tags:
      - Persons
      summary: Add a person to the given account
      description: 'Permissions

        HourlyProfile: Write

        Person: Write

        Private: Read

        Finance: Read'
      operationId: Persons_Post
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        description: 'Details for the person object and any associated custom field values. Note: the title must be one of the titles already defined on the account.'
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/NewPersonRequest'
            example:
              email: jayne@example.com
              uniqueId: jayne@example.com
              name: Jayne Peters
              type: Salaried
              title: Project Engineer
              photoUrl: https://www.example.com/jayne.png
              employmentDates:
                StartDate: '2020-01-01T00:00:00'
                EndDate: '2020-12-31T00:00:00'
              workDays:
              - 1
              - 2
              - 3
              - 4
              - 5
              fields:
              - fieldId: 1394
                values:
                - '5195555555'
              groupings: null
              industryStartDate: null
          application/json:
            schema:
              $ref: '#/components/schemas/NewPersonRequest'
            example:
              email: jayne@example.com
              uniqueId: jayne@example.com
              name: Jayne Peters
              type: Salaried
              title: Project Engineer
              photoUrl: https://www.example.com/jayne.png
              employmentDates:
                StartDate: '2020-01-01T00:00:00'
                EndDate: '2020-12-31T00:00:00'
              workDays:
              - 1
              - 2
              - 3
              - 4
              - 5
              fields:
              - fieldId: 1394
                values:
                - '5195555555'
              groupings: null
              industryStartDate: null
          text/json:
            schema:
              $ref: '#/components/schemas/NewPersonRequest'
            example:
              email: jayne@example.com
              uniqueId: jayne@example.com
              name: Jayne Peters
              type: Salaried
              title: Project Engineer
              photoUrl: https://www.example.com/jayne.png
              employmentDates:
                StartDate: '2020-01-01T00:00:00'
                EndDate: '2020-12-31T00:00:00'
              workDays:
              - 1
              - 2
              - 3
              - 4
              - 5
              fields:
              - fieldId: 1394
                values:
                - '5195555555'
              groupings: null
              industryStartDate: null
          application/*+json:
            schema:
              $ref: '#/components/schemas/NewPersonRequest'
            example:
              email: jayne@example.com
              uniqueId: jayne@example.com
              name: Jayne Peters
              type: Salaried
              title: Project Engineer
              photoUrl: https://www.example.com/jayne.png
              employmentDates:
                StartDate: '2020-01-01T00:00:00'
                EndDate: '2020-12-31T00:00:00'
              workDays:
              - 1
              - 2
              - 3
              - 4
              - 5
              fields:
              - fieldId: 1394
                values:
                - '5195555555'
              groupings: null
              industryStartDate: null
        required: true
      responses:
        '200':
          description: 'Success: Person model of the newly added person'
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PersonResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/PersonResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/PersonResponse'
        '400':
          description: Bad Request - Request has missing or invalid values
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User doesn't have permissions on this resource, or the account couldn't be found
        '409':
          description: Conflict - A person with the provided email already exists on the account
        '422':
          description: Unprocessable Entity - Validation failure
  /rp/api/v1/accounts/{accountId}/Persons/availabilities:
    get:
      tags:
      - Persons
      summary: Gets the number of days until each person in this account is available and…
      description: 'Permissions

        HourlyProfile: Read

        Person: Read'
      operationId: Persons_QueryNextAvailables
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: relativeDate
        in: query
        description: Optional paramater used to calculate date based properties. If not provided, it is set to today's date in UTC.
        schema:
          type: string
          format: date-time
          example: '2021-01-01'
        example: '2021-01-01'
      - name: start
        in: query
        description: Start date to filter availabilities from (default today UTC)
        schema:
          type: string
          format: date-time
      - name: end
        in: query
        description: End date to filter availabilities to (default 10 years from today UTC)
        schema:
          type: string
          format: date-time
      - name: boundRange
        in: query
        description: Setting this value to true will truncate the dates returned to the specified start and end date paramters
        schema:
          type: boolean
          default: true
      - name: ids
        in: query
        description: Optional paramater of comma delimited ids for filtering results based on the person IDs provided
        schema:
          type: array
          items:
            type: integer
            format: int64
      - name: includeUnavailable
        in: query
        description: 'If this is set to true it will return the availabilities and next available dates even if a person doesn''t have a next availability.

          If the person does not have a "nextAvailableDate", then the "availableInDays" property will be -1'
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: 'Success: List of next availabilities'
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonNextAvailable'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonNextAvailable'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonNextAvailable'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /rp/api/v1/accounts/{accountId}/Persons/{id}/externalId:
    put:
      tags:
      - Persons
      summary: Updates a person to set and externalId that can be referenced by external…
      operationId: Persons_SetExternalId
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: id
        in: path
        description: The person ID
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Details for the person object
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ExternalIdRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalIdRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/ExternalIdRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ExternalIdRequest'
        required: true
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /rp/api/v1/accounts/{accountId}/Persons/_filter:
    post:
      tags:
      - Persons
      summary: Gets all people in the given account filter by person ids
      description: 'NOTE: If there are more persons in the account than were returned, there will be a "query-has-more" header that will be set to true.

        Permissions

        HourlyProfile: Read

        Person: Read

        Finance: Read'
      operationId: Persons_QueryFilter
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        description: Filter object including personIds, state, email, uniqueId, relativeDate, offset and limit
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/PersonFilterPredicatesFilter'
          application/json:
            schema:
              $ref: '#/components/schemas/PersonFilterPredicatesFilter'
          text/json:
            schema:
              $ref: '#/components/schemas/PersonFilterPredicatesFilter'
          application/*+json:
            schema:
              $ref: '#/components/schemas/PersonFilterPredicatesFilter'
        required: true
      responses:
        '200':
          description: 'Success: List of persons in the account'
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonResponse'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonResponse'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /rp/api/v1/accounts/{accountId}/Persons/{id}:
    patch:
      tags:
      - Persons
      summary: Update a person in the given account.
      description: 'Permissions

        Person: Write

        HourlyProfile: Write

        Finance: Read'
      operationId: Persons_Update
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: id
        in: path
        description: The Person ID
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: 'Details for the person object. Note: the title must be one of the titles already defined on the account.'
        content:
          application/json-patch+json:
            schema:
              type: object
              additionalProperties: {}
            example:
              Email: jayne@example.com
              UniqueId: This is a unique String Id
              Name: Jayne Peters
              Title: Project Engineer
              EmploymentDates:
                StartDate: '2020-01-01T00:00:00'
                EndDate: '2020-12-31T00:00:00'
              WorkDays:
              - 1
              - 2
              - 3
              - 4
              - 5
          application/json:
            schema:
              type: object
              additionalProperties: {}
            example:
              Email: jayne@example.com
              UniqueId: This is a unique String Id
              Name: Jayne Peters
              Title: Project Engineer
              EmploymentDates:
                StartDate: '2020-01-01T00:00:00'
                EndDate: '2020-12-31T00:00:00'
              WorkDays:
              - 1
              - 2
              - 3
              - 4
              - 5
          text/json:
            schema:
              type: object
              additionalProperties: {}
            example:
              Email: jayne@example.com
              UniqueId: This is a unique String Id
              Name: Jayne Peters
              Title: Project Engineer
              EmploymentDates:
                StartDate: '2020-01-01T00:00:00'
                EndDate: '2020-12-31T00:00:00'
              WorkDays:
              - 1
              - 2
              - 3
              - 4
              - 5
          application/*+json:
            schema:
              type: object
              additionalProperties: {}
            example:
              Email: jayne@example.com
              UniqueId: This is a unique String Id
              Name: Jayne Peters
              Title: Project Engineer
              EmploymentDates:
                StartDate: '2020-01-01T00:00:00'
                EndDate: '2020-12-31T00:00:00'
              WorkDays:
              - 1
              - 2
              - 3
              - 4
              - 5
        required: true
      responses:
        '200':
          description: 'Success: Person model of the updated person'
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PersonResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/PersonResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/PersonResponse'
        '400':
          description: Bad Request - Request has missing or invalid values
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User doesn't have permissions on this resource, or the person or account couldn't be found
        '409':
          description: Conflict - A person with the provided email already exists on the account
        '422':
          description: Unprocessable Entity - Validation failure
    get:
      tags:
      - Persons
      summary: Gets details for the given person
      description: 'Permissions

        Finance: Read

        Person: Read

        HourlyProfile: Read'
      operationId: Persons_Get
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: id
        in: path
        description: The Person ID
        required: true
        schema:
          type: integer
          format: int64
      - name: relativeDate
        in: query
        description: Optional paramater used to calculate date based properties. If not provided, it is set to today's date in UTC.
        schema:
          type: string
          format: date-time
          example: '2021-01-01'
        example: '2021-01-01'
      responses:
        '200':
          description: 'Success: Person Model for the requested person'
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PersonResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/PersonResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/PersonResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    delete:
      tags:
      - Persons
      summary: Deactivate a person
      description: 'Permissions

        Person: Write

        HourlyProfile: Write'
      operationId: Persons_Delete
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: id
        in: path
        description: The Person ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '204':
          description: No Content (success)
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User doesn't have permissions on this resource, or the account couldn't be found
  /rp/api/v1/accounts/{accountId}/Persons/{id}/deactivate:
    post:
      tags:
      - Persons
      summary: Deactivate a person with optional deactivation details (reason, notes, would…
      description: 'Permissions

        Person: Write

        HourlyProfile: Write'
      operationId: Persons_Deactivate
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: id
        in: path
        description: The Person ID
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Optional deactivation details
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/PersonDeactivateRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/PersonDeactivateRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/PersonDeactivateRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/PersonDeactivateRequest'
      responses:
        '204':
          description: No Content (success)
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User doesn't have permissions on this resource, or the account couldn't be found
  /rp/api/v1/accounts/{accountId}/Persons/{id}/allocations:
    get:
      tags:
      - Persons
      summary: Get all allocations for the given person within the selected date range
      description: 'Permissions

        Role: Read

        HourlyRole: Read

        Allocation: Read

        HourlyAllocation: Read

        Person: Read

        HourlyProfile: Read'
      operationId: Persons_GetAllocations
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: id
        in: path
        description: The Person's ID
        required: true
        schema:
          type: integer
          format: int64
      - name: relativeDate
        in: query
        description: Optional paramater used to calculate date based properties. If not provided, it is set to today's date in UTC.
        schema:
          type: string
          format: date-time
          example: '2021-01-01'
        example: '2021-01-01'
      - name: start
        in: query
        description: Start date to filter allocations from
        schema:
          type: string
          format: date-time
      - name: end
        in: query
        description: End date to filter allocations to
        schema:
          type: string
          format: date-time
      - name: roleId
        in: query
        description: Optional parameter to get allocations for a specific role
        schema:
          type: integer
          format: int32
      - name: projectState
        in: query
        description: Optional parameter for filtering results by project state.
        schema:
          enum:
          - Canceled
          - Upcoming
          - Active
          - Complete
          - Pursuit
          - Lost
          - All
          type: string
          default: All
      - name: type
        in: query
        description: Optional parameter Salaried role type to filter results by (Default to Operations)
        schema:
          enum:
          - Operations
          - Preconstruction
          - All
          type: string
          default: Operations
      responses:
        '200':
          description: 'Success: List of allocations'
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonAllocationResponse'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonAllocationResponse'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonAllocationResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /rp/api/v1/accounts/{accountId}/Persons/{id}/projects:
    get:
      tags:
      - Persons
      summary: Get all projects that this person is allocated to, including past, present, and…
      description: 'Permissions

        Person: Read

        HourlyProfile: Read

        Allocation: Read

        HourlyAllocation: Read'
      operationId: Persons_GetProjects
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: id
        in: path
        description: The Person ID
        required: true
        schema:
          type: integer
          format: int64
      - name: relativeDate
        in: query
        description: Optional paramater used to calculate date based properties. If not provided, it is set to today's date in UTC.
        schema:
          type: string
          format: date-time
          example: '2021-01-01'
        example: '2021-01-01'
      - name: projectState
        in: query
        description: Optional parameter for filtering results by project state.
        schema:
          enum:
          - Canceled
          - Upcoming
          - Active
          - Complete
          - Pursuit
          - Lost
          - All
          type: string
          default: All
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonProjectResponse'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonProjectResponse'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonProjectResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /rp/api/v1/accounts/{accountId}/Persons/current-projects:
    get:
      tags:
      - Persons
      summary: Get all projects that any person in the given account has an active allocation…
      description: 'Permissions

        Person: Read

        Allocation: Read'
      operationId: Persons_GetCurrentProjects
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: relativeDate
        in: query
        description: Optional paramater used to calculate date based properties. If not provided, it is set to today's date in UTC.
        schema:
          type: string
          format: date-time
          example: '2021-01-01'
        example: '2021-01-01'
      - name: personIds
        in: query
        description: Optional paramater of comma delimited ids for filtering results based on the person IDs provided
        schema:
          type: array
          items:
            type: integer
            format: int64
      - name: projectState
        in: query
        description: Optional parameter for filtering results by project state.
        schema:
          enum:
          - Canceled
          - Upcoming
          - Active
          - Complete
          - Pursuit
          - Lost
          - All
          type: string
          default: All
      - name: type
        in: query
        description: (Optional)Salaried role type to filter results by (Defaults to All)
        schema:
          enum:
          - Operations
          - Preconstruction
          - All
          type: string
          default: All
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonProjectList'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonProjectList'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonProjectList'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /rp/api/v1/accounts/{accountId}/Persons/current-projects-hourly:
    get:
      tags:
      - Persons
      summary: Get all projects that any person in the given account has an active allocation…
      description: 'Permissions

        HourlyProfile: Read

        HourlyAllocation: Read'
      operationId: Persons_GetCurrentProjectsHourly
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: relativeDate
        in: query
        description: Optional paramater used to calculate date based properties. If not provided, it is set to today's date in UTC.
        schema:
          type: string
          format: date-time
          example: '2021-01-01'
        example: '2021-01-01'
      - name: personIds
        in: query
        description: Optional paramater of comma delimited ids for filtering results based on the person IDs provided
        schema:
          type: array
          items:
            type: integer
            format: int64
      - name: projectState
        in: query
        description: Optional parameter for filtering results by project state.
        schema:
          enum:
          - Canceled
          - Upcoming
          - Active
          - Complete
          - Pursuit
          - Lost
          - All
          type: string
          default: All
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonProjectList'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonProjectList'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonProjectList'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /rp/api/v1/accounts/{accountId}/Persons/{id}/restore:
    post:
      tags:
      - Persons
      summary: Reactivate a person
      description: 'Permissions

        Person: Write

        HourlyProfile: Write

        Finance: Read'
      operationId: Persons_Restore
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: id
        in: path
        description: The Person ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '204':
          description: No Content (success)
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User doesn't have permissions on this resource, or the account couldn't be found
        '422':
          description: Validation failure - The person is already active in the account
components:
  schemas:
    EmploymentDatesResponse:
      type: object
      properties:
        startDate:
          type:
          - string
          - 'null'
          format: date-time
        endDate:
          type:
          - string
          - 'null'
          format: date-time
      additionalProperties: false
    PersonNextAvailable:
      type: object
      properties:
        personId:
          type: integer
          format: int64
          example: 8673
        nextAvailableDate:
          type:
          - string
          - 'null'
          format: date-time
          example: '2019-01-01'
        availableInDays:
          type: integer
          format: int32
          example: 82
        availabilities:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Availability'
      additionalProperties: false
    PersonAllocationResponse:
      type: object
      properties:
        projectId:
          type: integer
          format: int64
        projectName:
          type:
          - string
          - 'null'
        projectColour:
          type:
          - string
          - 'null'
        projectType:
          enum:
          - Awarded
          - Opportunity
          type: string
        projectStatus:
          enum:
          - Canceled
          - Upcoming
          - Active
          - Complete
          - Pursuit
          - Lost
          type:
          - string
          - 'null'
        taskId:
          type:
          - string
          - 'null'
          format: uuid
        roleId:
          type: integer
          format: int64
        roleName:
          type:
          - string
          - 'null'
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        allocatedPercent:
          type: integer
          format: int32
      additionalProperties: false
    PersonProjectList:
      type: object
      properties:
        personId:
          type: integer
          format: int64
          example: 8673
        projects:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Project'
      additionalProperties: false
    PersonFilterPredicatesFilter:
      type: object
      properties:
        offset:
          type: integer
          format: int32
        limit:
          type: integer
          format: int32
        predicates:
          $ref: '#/components/schemas/PersonFilterPredicates'
      additionalProperties: false
    PersonDeactivateRequest:
      type: object
      properties:
        deactivationReason:
          maxLength: 100
          minLength: 0
          type:
          - string
          - 'null'
        deactivationNotes:
          maxLength: 240
          minLength: 0
          type:
          - string
          - 'null'
        wouldRehire:
          type:
          - boolean
          - 'null'
        employmentEndDate:
          type:
          - string
          - 'null'
          format: date-time
      additionalProperties: false
    PersonFilterPredicates:
      type: object
      properties:
        personIds:
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int64
        state:
          enum:
          - Active
          - Deactivated
          - All
          type: string
        email:
          type:
          - string
          - 'null'
        uniqueId:
          type:
          - string
          - 'null'
        relativeDate:
          type: string
          format: date-time
      additionalProperties: false
    PersonResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type:
          - string
          - 'null'
        externalId:
          type:
          - string
          - 'null'
        uniqueId:
          type:
          - string
          - 'null'
        name:
          type:
          - string
          - 'null'
        type:
          enum:
          - Salaried
          - Hourly
          type: string
        title:
          type:
          - string
          - 'null'
        photoUrl:
          type:
          - string
          - 'null'
        state:
          enum:
          - Active
          - Deactivated
          - All
          type: string
        hasConflict:
          type: boolean
          readOnly: true
        nextConflict:
          type:
          - string
          - 'null'
          format: date-time
        lastModifiedOn:
          type: string
          format: date-time
        hourlyCostRate:
          type:
          - number
          - 'null'
          format: double
        employmentDates:
          $ref: '#/components/schemas/EmploymentDatesResponse'
        workDays:
          type:
          - array
          - 'null'
          items:
            enum:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            type: integer
            format: int32
        groupings:
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int64
        industryStartDate:
          type:
          - string
          - 'null'
          format: date-time
        deactivationReason:
          type:
          - string
          - 'null'
        deactivationNotes:
          type:
          - string
          - 'null'
        wouldRehire:
          type:
          - boolean
          - 'null'
      additionalProperties: false
    Availability:
      type: object
      properties:
        startDate:
          type: string
          format: date-time
          example: '2021-01-01'
        endDate:
          type: string
          format: date-time
          example: '2021-12-31'
        availablePercent:
          type:
          - integer
          - 'null'
          format: int32
          example: 100
        reason:
          enum:
          - Available
          - Allocated
          - PreEmployment
          - PostEmployment
          - Unavailability
          type:
          - string
          - 'null'
      additionalProperties: false
    Project:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 9381
        name:
          type:
          - string
          - 'null'
          example: Ahrens Lofts
        colour:
          type:
          - string
          - 'null'
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        projectType:
          enum:
          - Awarded
          - Opportunity
          type: string
        state:
          enum:
          - Canceled
          - Upcoming
          - Active
          - Complete
          - Pursuit
          - Lost
          type: string
          readOnly: true
      additionalProperties: false
    ExternalIdRequest:
      type: object
      properties:
        externalId:
          type:
          - string
          - 'null'
      additionalProperties: false
    FieldValuesPair:
      type: object
      properties:
        fieldId:
          type: integer
          format: int64
          example: 1394
        values:
          type:
          - array
          - 'null'
          items:
            type: string
          example:
          - '5195555555'
      additionalProperties: false
    PersonProjectResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 8673
        name:
          type:
          - string
          - 'null'
          example: Ahrens Lofts
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        projectType:
          enum:
          - Awarded
          - Opportunity
          type: string
        projectStatus:
          enum:
          - Canceled
          - Upcoming
          - Active
          - Complete
          - Pursuit
          - Lost
          type: string
      additionalProperties: false
    NewPersonRequest:
      type: object
      properties:
        email:
          type:
          - string
          - 'null'
          format: email
          example: jayne@example.com
        uniqueId:
          type:
          - string
          - 'null'
          example: This is a unique string that is less than 255 characters
        name:
          maxLength: 250
          minLength: 1
          type:
          - string
          - 'null'
          example: Jayne Peters
        type:
          enum:
          - Salaried
          - Hourly
          type: string
          example: Salaried
        title:
          maxLength: 250
          minLength: 1
          type:
          - string
          - 'null'
          example: Project Engineer
        photoUrl:
          type:
          - string
          - 'null'
          format: uri
          example: https://www.example.com/jayne.png
        employmentDates:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - string
            - 'null'
            format: date-time
          description: Request object for representing employment dates on a person.
        workDays:
          minItems: 1
          type:
          - array
          - 'null'
          items:
            enum:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            type: integer
            format: int32
          default:
          - 1
          - 2
          - 3
          - 4
          - 5
          example:
          - 1
          - 2
          - 3
          - 4
          - 5
        fields:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/FieldValuesPair'
        groupings:
          minItems: 1
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int64
        industryStartDate:
          type:
          - string
          - 'null'
          format: date-time
          example: '2020-01-01T00:00:00Z'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      description: Standard Authorization header using the Bearer scheme
      scheme: bearer
      bearerFormat: JWT
